#!/usr/bin/env bash
# configure web-02 to web-01
# The name the custom HTTP header X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
#sudo sed -i 's/server_name _;.*/server_ame _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		 try_files \$uri \$uri/ =404;
		 }
		 if (\$request_filename ~ redirect_me){
		    rewrite ^ https://youtube.com permanent;
		    }
		    error_page 404 /404.html;
		    location = /404.html {
		    	     internal;
			     }
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart  
fi
