#!/usr/bin/env bash
# Configue ufw to block all incoming traffic, except the TCP port 22, 80, 443
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw enable -y
sudo ufw default allow outgoing -y
sudo ufw default deny incoming -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
